[build]
  functions = "functions"
  node_bundler = "esbuild"
[[headers]]
  for = "/api/*"
[headers.values]
    Cache-Control = "no-cache"
    X-Content-Type-Options = "nosniff"
[[functions.schedules]]
  cron = "*/1 * * * *"
  function = "cron"
