[build]
  functions = "functions"
  node_bundler = "esbuild"
[functions]
  node_bundler = "esbuild"
  include_files = [
    "commercetools/**",
    "package.json",
    "tsconfig.json" 
  ]
[[headers]]
  for = "/api/*"
[headers.values]
    Cache-Control = "no-cache"
    X-Content-Type-Options = "nosniff"
