[build]
  functions = "functions"
  node_bundler = "esbuild"
[[headers]]
  for = "/api/*"
[headers.values]
    Cache-Control = "no-cache"
    X-Content-Type-Options = "nosniff"
[functions."validate-status"]
  schedule = "*/1 * * * *"  # cada minuto (ajusta según necesidad)
