[build]
  functions = "functions"  # O donde estén tus funciones
  publish = "functions"         # Carpeta que Netlify debe desplegar
  command = "npm run build" # Comando para compilar el TypeScript
